# Generated by Django 5.1.4 on 2025-01-02 13:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('total_employees', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_rank', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='co2champion_database_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=4096)),
                ('description', models.TextField()),
                ('year', models.IntegerField(null=True)),
                ('released', models.DateField(default=datetime.date.today)),
                ('run_time', models.PositiveIntegerField(help_text='in minutes')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('black_and_white', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(to='co2champion_database_app.genre')),
                ('actors', models.ManyToManyField(related_name='actors', to='co2champion_database_app.person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director', to='co2champion_database_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='co2champion_database_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('date', models.DateField()),
                ('reduced_emissions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='co2champion_database_app.company')),
            ],
        ),
    ]
