# Generated by Django 5.1.2 on 2025-01-25 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_employees', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_rank', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='co2champion_database_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='co2champion_database_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('date', models.DateField()),
                ('reduced_emissions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='co2champion_database_app.company')),
            ],
        ),
    ]
