# Generated by Django 5.1.4 on 2024-12-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2champion_database_app', '0010_movie_black_and_white'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('total_employees', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('start_date', models.DateField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='co2champion_database_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('date', models.DateField()),
                ('reduced_emissions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='co2champion_database_app.company')),
            ],
        ),
    ]
