# Generated by Django 5.1.4 on 2024-12-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2champion_database_app', '0011_company_goal_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='rank',
            new_name='current_rank',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='current_emissions',
            new_name='start_emissions',
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='co2champion_database_app.company')),
            ],
        ),
    ]
