# Generated by Django 5.1.4 on 2024-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2champion_database_app', '0012_rename_rank_company_current_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankhistory',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
